theme: jekyll-theme-minimal
title: Hao Xiong <br>熊昊
description: Assistant Professor <br>AI3 Institute, Fudan University 
contacts: E-mail taxuexh AT sjtu.edu.cn <br>WeChat larosa4810
logo: /pics/me.jpg
street_workout_log: /pics/street_workout_log.jpeg
show_downloads: false
google_analytics: 
